# ~/.dotfiles/mise/.config/mise/config.toml

[tools]
node                = "24"
java                = "openjdk-25"
maven               = "3.9.14"
python              = "3.14"
"npm:@angular/cli"  = "21.2.7"
"npm:ccstatusline"  = "2.2.7"

opentofu            = "latest"
kubectl             = "latest"
helm                = "latest"

[settings]
trusted_config_paths  = [
  "~/.config/mise",
  "~/projects/",
]

idiomatic_version_file_enable_tools = [ "java", "node", "python" ]

[env]
MAVEN_OPTS="-Xmx512m"
