# ~/.dotfiles/mise/.config/mise/config.toml

[tools]
node                = "24"
pnpm                = "11.9.0"
java                = "openjdk-25"
maven               = "3.9.16"
quarkus             = "3.33"
python              = "3.14"
"uv"                = "0.11.24"
"npm:ccstatusline"  = "2.2.22"

"npm:@mermaid-js/mermaid-cli"    = "latest"
"npm:typescript"                 = "latest"
"npm:typescript-language-server" = "latest"

opentofu            = "latest"
kubectl             = "latest"
helm                = "latest"

[settings]
trusted_config_paths  = [
  "~/.config/mise",
  "~/projects/",
]

idiomatic_version_file_enable_tools = [ "java", "node", "python" ]

[env]
MAVEN_OPTS="-Xmx512m"
